### ISSUE TITLE
HTML5 video

### ISSUE THREAD

**Issue by Kalmaasaly** [FredJul/Flym#194]
I have problem I cannot display the video using html5 
could anyone help in this issue
I/MediaPlayer﹕ path is null
    8298-8298/net.fred.feedex D/MediaPlayer﹕ setDataSource IOException happend :
    java.io.FileNotFoundException: No content provider: http:/url/.mp4
            at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:710)
            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:614)
            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:929)
            at android.webkit.HTML5VideoView.prepareDataCommon(HTML5VideoView.java:308)
            at android.webkit.HTML5VideoView.prepareDataAndDisplayMode(HTML5VideoView.java:345)
            at android.webkit.HTML5VideoInline.prepareDataAndDisplayMode(HTML5VideoInline.java:57)
            at android.webkit.HTML5VideoViewProxy$VideoPlayer.play(HTML5VideoViewProxy.java:256)
            at android.webkit.HTML5VideoViewProxy.handleMessage(HTML5VideoViewProxy.java:407)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4867)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)

**Comment by Kalmaasaly** [comment]
Thank you for your reply,
I have change the enclosure button into html5 video tag
Flym 1.7.3 the video's link works fine, but when I have change the version of Flym 1.7.4 does not work.

**Comment by Kalmaasaly** [comment]
Dear Sir ,

I need your help how could I delete or update the feed uri
I am making  customized app 
Thank you,

**Comment by Kalmaasaly** [comment]
Dear

I created a new activity in Flym app from this activity I want to delete selected item from drawer navigation's ListView
Please Help me
Thank you

**Comment by ildar** [comment]
How does that relate to HTML video issue?
