### ISSUE TITLE
Flym is crashing

### ISSUE THREAD

**Issue by aelmahmoudy** [FredJul/Flym#218]
Here's the logcat:

```
I/ActivityManager( 2389): Displayed net.fred.feedex/.activity.HomeActivity: +443ms
W/AudioService( 2389): stream was not muted by this client
E/AudioService( 2389): Could not get client death handler for stream: 3
W/AudioService( 2389): stream was not muted by this client
E/AudioService( 2389): Could not get client death handler for stream: 3
I/HK/LatinKeyboardBaseView( 7852): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{41c12668 V.ED.... ......ID 0,0-1280,395 #7f07000a app:id/LatinkeyboardBase
View}
W/Settings(22661): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/dalvikvm(22661): GC_FOR_ALLOC freed 463K, 10% free 5473K/6020K, paused 10ms, total 10ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 11.009MB for 5880016-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed 32K, 5% free 11183K/11764K, paused 8ms, total 8ms
D/dalvikvm(22661): GC_CONCURRENT freed 58K, 6% free 11148K/11764K, paused 2ms+3ms, total 15ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 24K, 5% free 11202K/11764K, paused 10ms, total 10ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 13.791MB for 2931452-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed 0K, 4% free 14064K/14628K, paused 10ms, total 10ms
D/dalvikvm(22661): GC_CONCURRENT freed 72K, 4% free 15194K/15728K, paused 2ms+3ms, total 19ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 1968K, 13% free 16581K/18996K, paused 10ms, total 10ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 32K, 12% free 18451K/20820K, paused 11ms, total 11ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 37.112MB for 19961872-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed 2862K, 13% free 35082K/40316K, paused 10ms, total 10ms
D/dalvikvm(22661): GC_CONCURRENT freed 32K, 13% free 35116K/40316K, paused 2ms+3ms, total 18ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 40.876MB for 8294416-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed 1914K, 22% free 39886K/50692K, paused 11ms, total 11ms
D/dalvikvm(22661): GC_CONCURRENT freed 62K, 20% free 40698K/50692K, paused 1ms+3ms, total 15ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 5051K, 23% free 39254K/50692K, paused 12ms, total 12ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 1K, 14% free 43810K/50692K, paused 13ms, total 13ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 47.289MB for 4665616-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed 0K, 13% free 48366K/55252K, paused 12ms, total 12ms
D/dalvikvm(22661): GC_FOR_ALLOC freed 12736K, 12% free 35630K/40272K, paused 15ms, total 15ms
I/dalvikvm-heap(22661): Grow heap (frag case) to 47.543MB for 13307920-byte allocation
D/dalvikvm(22661): GC_FOR_ALLOC freed <1K, 9% free 48626K/53272K, paused 13ms, total 13ms
D/dalvikvm(22661): GC_CONCURRENT freed 1K, 9% free 48625K/53272K, paused 2ms+4ms, total 20ms
D/dalvikvm(22661): WAIT_FOR_CONCURRENT_GC blocked 18ms
I/dalvikvm-heap(22661): Forcing collection of SoftReferences for 13307920-byte allocation
D/dalvikvm(22661): GC_BEFORE_OOM freed 72K, 9% free 48552K/53272K, paused 24ms, total 24ms
E/dalvikvm-heap(22661): Out of memory on a 13307920-byte allocation.
I/dalvikvm(22661): "Picasso-/data/data/net.fred.feedex/cache/images/4827__f15776108aad5034e91568b7c0bc5f75" prio=5 tid=20 RUNNABLE
I/dalvikvm(22661):   | group="main" sCount=0 dsCount=0 obj=0x41e68128 self=0x5d781c48
I/dalvikvm(22661):   | sysTid=22688 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1577175464
I/dalvikvm(22661):   | state=R schedstat=( 220386207 142744252 181 ) utm=13 stm=8 core=1
I/dalvikvm(22661):   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
I/dalvikvm(22661):   at android.graphics.Bitmap.nativeCreate(Native Method)
I/dalvikvm(22661):   at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
I/dalvikvm(22661):   at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
I/dalvikvm(22661):   at android.graphics.Bitmap.createBitmap(Bitmap.java:708)
I/dalvikvm(22661):   at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
I/dalvikvm(22661):   at net.fred.feedex.utils.CircleTransform.a(SourceFile:43)
I/dalvikvm(22661):   at com.squareup.picasso.BitmapHunter.a(SourceFile:429)
I/dalvikvm(22661):   at com.squareup.picasso.BitmapHunter.a(SourceFile:238)
I/dalvikvm(22661):   at com.squareup.picasso.BitmapHunter.run(SourceFile:159)
I/dalvikvm(22661):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
I/dalvikvm(22661):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
I/dalvikvm(22661):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I/dalvikvm(22661):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I/dalvikvm(22661):   at java.lang.Thread.run(Thread.java:841)
I/dalvikvm(22661):   at com.squareup.picasso.Utils$PicassoThread.run(SourceFile:394)
I/dalvikvm(22661): 
E/dalvikvm(22661): JNI ERROR (app bug): accessed stale local reference 0x1e300009 (index 2 in a table of size 1)
E/dalvikvm(22661): VM aborting
F/libc    (22661): Fatal signal 6 (SIGABRT) at 0x00005885 (code=-6), thread 22688 (Thread-2146)
I/DEBUG   ( 1938): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

W/ActivityManager( 2389):   Force finishing activity net.fred.feedex/.activity.HomeActivity
W/InputDispatcher( 2389): channel '43236fa0 net.fred.feedex/net.fred.feedex.activity.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 2389): channel '43236fa0 net.fred.feedex/net.fred.feedex.activity.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
D/Zygote  ( 1941): Process 22661 terminated by signal (6)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
W/InputDispatcher( 2389): Attempted to unregister already unregistered input channel '43236fa0 net.fred.feedex/net.fred.feedex.activity.HomeActivity (server)'
I/WindowState( 2389): WIN DEATH: Window{43236fa0 u0 net.fred.feedex/net.fred.feedex.activity.HomeActivity}
D/dalvikvm( 2389): GC_FOR_ALLOC freed 3509K, 28% free 20267K/28100K, paused 65ms, total 66ms
W/ActivityManager( 2389): Exception thrown during pause
W/ActivityManager( 2389): android.os.DeadObjectException
W/ActivityManager( 2389):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager( 2389):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager( 2389):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager( 2389):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2443)
W/ActivityManager( 2389):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2320)
W/ActivityManager( 2389):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2050)
W/ActivityManager( 2389):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9548)
W/ActivityManager( 2389):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9441)
W/ActivityManager( 2389):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10086)
W/ActivityManager( 2389):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9637)
W/ActivityManager( 2389):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager( 2389): Process net.fred.feedex (pid 22661) has died.
W/ActivityManager( 2389): Scheduling restart of crashed service net.fred.feedex/.service.RefreshService in 1000ms
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)
E/GLConsumer( 1940): [net.fred.feedex/net.fred.feedex.activity.HomeActivity] doGLFenceWait: error waiting for fence: -2
W/SurfaceFlinger( 1940): onDraw: bindTextureImage failed (err=-2)

```

**Comment by suyash1629** [comment]
it seems like the issue is with the loading of image in the entry list view. Your phone is "Out of memory on a 13307920-byte allocation."
