### ISSUE TITLE
App Crashes when trying to load certain articles

### ISSUE THREAD

**Issue by zenzora** [FredJul/Flym#343]
Wow, thought V2 was a myth. Thanks for maintaining this!

The app seems to crash every once in awhile. Sometimes on start, sometimes I start to scroll down and it crashes when it gets to a certain article. It will also crash when viewing the affected article itself. This was something I've dealt with from time to time over the past few years but usually I just wait till need feeds load and push the article down. I have a hunch its encountering it when trying to load large resources (PDF, MP4...).  It may also have to do with having fetching the full text

This usually happens with hacker-news or lobsters links so sometimes its hard to find the exact article thats causing the crash. I'll add more details when I can find the exact article its crashing on

LogCat Dump:

Device: Sony Xperia XA2 running Oreo (this also used to happen with V1 on my oneplus 1)
```
07-10 12:12:05.191  1543  3106 I ActivityManager: Start proc 13802:net.frju.flym/u0a197 for activity net.frju.flym/.ui.main.MainActivity
07-10 12:12:05.566 13802 13823 D OpenGLRenderer: HWUI GL Pipeline
07-10 12:12:05.620 13802 13823 I Adreno  : QUALCOMM build                   : 1dcb581, I26dffed9a4
07-10 12:12:05.620 13802 13823 I Adreno  : Build Date                       : 01/10/18
07-10 12:12:05.620 13802 13823 I Adreno  : OpenGL ES Shader Compiler Version: EV031.22.00.01
07-10 12:12:05.620 13802 13823 I Adreno  : Local Branch                     : 
07-10 12:12:05.620 13802 13823 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.4.R1.08.00.00.309.049
07-10 12:12:05.620 13802 13823 I Adreno  : Remote Branch                    : NONE
07-10 12:12:05.620 13802 13823 I Adreno  : Reconstruct Branch               : NOTHING
07-10 12:12:05.622 13802 13802 W RenderThread: type=1400 audit(0.0:60864): avc: denied { search } for name="proc" dev="debugfs" ino=4969 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0 ppid=714 pcomm="main" pgid=13802 pgcomm="net.frju.flym"
07-10 12:12:05.635 13802 13823 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
07-10 12:12:05.640 13802 13823 I OpenGLRenderer: Initialized EGL, version 1.4
07-10 12:12:05.640 13802 13823 D OpenGLRenderer: Swap behavior 2
07-10 12:12:05.678 13802 13824 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-10 12:12:05.718 13802 13808 I zygote64: Do partial code cache collection, code=20KB, data=30KB
07-10 12:12:05.719 13802 13808 I zygote64: After code cache collection, code=20KB, data=30KB
07-10 12:12:05.719 13802 13808 I zygote64: Increasing code cache capacity to 128KB
07-10 12:12:05.913 13802 13822 W CursorWindow: Window is full: requested allocation 3976196 bytes, free space 1820957 bytes, window size 2097152 bytes
07-10 12:12:05.923 13802 13808 I zygote64: Do partial code cache collection, code=60KB, data=46KB
07-10 12:12:05.924 13802 13808 I zygote64: After code cache collection, code=60KB, data=46KB
07-10 12:12:05.924 13802 13808 I zygote64: Increasing code cache capacity to 256KB
07-10 12:12:05.987 13802 13827 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
07-10 12:12:05.988 13802 13827 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
07-10 12:12:05.988 13802 13827 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
07-10 12:12:06.013 13802 13822 W CursorWindow: Window is full: requested allocation 3976196 bytes, free space 2005245 bytes, window size 2097152 bytes
07-10 12:12:06.013 13802 13822 W CursorWindow: Window is full: requested allocation 3976196 bytes, free space 2096029 bytes, window size 2097152 bytes
07-10 12:12:06.015 13802 13822 E CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 22 columns.
07-10 12:12:06.019 13802 13822 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
07-10 12:12:06.019 13802 13822 E AndroidRuntime: Process: net.frju.flym, PID: 13802
07-10 12:12:06.019 13802 13822 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.database.CursorWindow.nativeGetString(Native Method)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.database.CursorWindow.getString(CursorWindow.java:438)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at net.frju.flym.data.dao.EntryDao_Impl$10$1.convertRows(SourceFile:595)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.persistence.room.paging.LimitOffsetDataSource.loadRange(SourceFile:168)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.persistence.room.paging.LimitOffsetDataSource.loadInitial(SourceFile:119)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.PositionalDataSource.dispatchLoadInitial(SourceFile:286)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.TiledPagedList.<init>(SourceFile:98)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.PagedList.create(SourceFile:203)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.PagedList.access$000(SourceFile:114)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.PagedList$Builder.build(SourceFile:362)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.LivePagedListBuilder$1.compute(SourceFile:201)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.paging.LivePagedListBuilder$1.compute(SourceFile:166)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at android.arch.lifecycle.ComputableLiveData$2.run(SourceFile:100)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-10 12:12:06.019 13802 13822 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-10 12:12:06.418 13802 13802 D Activity: [STKTB]onDestroy - ClassName = net.frju.flym.ui.main.MainActivity
07-10 12:12:06.600 13802 13808 I zygote64: Do full code cache collection, code=125KB, data=86KB
07-10 12:12:06.607 13802 13808 I zygote64: After code cache collection, code=64KB, data=38KB
07-10 12:12:06.680 13802 13828 I zygote64: Deoptimizing int org.jdom2.ContentList$FilterList.resync(int) due to JIT inline cache
07-10 12:12:06.680 13802 13828 I zygote64: Deoptimizing org.jdom2.Content org.jdom2.ContentList$FilterList.get(int) due to JIT inline cache
07-10 12:12:06.793 13802 13827 I zygote64: Deoptimizing void org.jdom2.ContentList.add(int, org.jdom2.Content) due to JIT inline cache
07-10 12:12:09.562  1543  3094 I ActivityManager: Killing 13802:net.frju.flym/u0a197 (adj 900): crash
```

**Comment by FredJul** [comment]
Hi,

Thank you for this report!
I just published an update which may fix that problem. I would be curious
to know if the problem disappeared for you after the update (you may need
to wait few hours to see the update).

Regards,
Fred

**Comment by FredJul** [comment]
I'm closing that issue since it seems I don't receive this crash anymore on the Google Play Dev Console
