### ISSUE TITLE
SQLiteException index_feeds_groupId already exists

### ISSUE THREAD

**Issue by ildar** [FredJul/Flym#379]
db changed with the tool from https://github.com/FredJul/Flym/pull/378
now Flym crashes :(
```
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: android.database.sqlite.SQLiteException: index index_feeds_groupId already exists (code 1): , while compiling: CREATE  INDEX `index_feeds_groupId` ON `feeds` (`groupId`)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(SourceFile:242)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at net.frju.flym.data.AppDatabase_Impl$1.createAllTables(SourceFile:43)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.room.RoomOpenHelper.onCreate(SourceFile:73)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(SourceFile:127)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(SourceFile:96)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(SourceFile:54)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.persistence.room.RoomDatabase.query(SourceFile:233)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at net.frju.flym.data.dao.FeedDao_Impl$7.compute(SourceFile:468)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at net.frju.flym.data.dao.FeedDao_Impl$7.compute(SourceFile:454)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at android.arch.lifecycle.ComputableLiveData$2.run(SourceFile:100)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.025  9595  9731 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
Tue, 04 Sep 2018 17:48:29 +0600: 09-04 17:48:29.029  4613 11087 W ActivityManager:   Force finishing activity net.frju.flym/.ui.main.MainActivity
```

**Comment by ildar** [comment]
also
> Tue, 04 Sep 2018 18:15:41 +0600: 09-04 18:15:41.547  9742 11041 E AndroidRuntime: android.database.sqlite.SQLiteException: index index_feeds_feedId_feedLink already exists (code 1): , while compiling: CREATE UNIQUE INDEX `index_feeds_feedId_feedLink` ON `feeds` (`feedId`, `feedLink`)

**Comment by ildar** [comment]
and finally
> Tue, 04 Sep 2018 18:23:14 +0600: 09-04 18:23:14.251 11445 11531 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode

this one probably because the Android sqlite3 is older then the host's.
The previous might be because I force-stopped Flym. What do you think?

Tomorrow I'll try to run the script on Android itself.

**Comment by FredJul** [comment]
is that problem still possible after your last fix?

**Comment by ildar** [comment]
no, my last commit kinda fixes that.
But I don't know if the problem can appear in/for other cases/users.

**Comment by FredJul** [comment]
Then I guess I can close it until someone found a problem :)
