### ISSUE TITLE
Crash when clicking on "Import from OPML"

### ISSUE THREAD

**Issue by AlexanderRitter02** [FredJul/Flym#644]
## The bug
Flym crashes when clicking on `"Import from OPML"` or `"Export to OPML"` directly after first start.

The only thing I did was start the app, cancel the welcome message and click on the named buttons.
:x: It crashed

### Logcat logs
[.txt File](https://github.com/FredJul/Flym/files/5126416/Flym.crash.log.txt)
[Pastebin](https://pastebin.com/Ztzgdtvx)
<details>
<summary>View directly on Github</summary>

```
08-25 23:34:01.418 20216 20216 D OnePlusJankManager:  Chor uploadMDM JANK_TYPE_NODRAW mViewTitle = net.frju.flym/net.frju.flym.ui.main.MainActivity--- jank level = 2
08-25 23:34:01.711  3178  5982 E ExecutionCriteria: Package unavailable for task: com.google.android.apps.tachyon/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="GrowthKit.StorageCleanupJob" trigger=window{start=82080s,end=90720s,earliest=-41141s,latest=-32501s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=-123221s last_run=-123221s jid=N/A status=PENDING retries=0 client_lib=FIREBASE_JOB_DISPATCHER-1} [CONTEXT service_id=218 ]
08-25 23:34:01.926   840  4228 E oemlogkit: oemlogkit: Android log path: (null). Inside
08-25 23:34:01.927   840  4228 E oemlogkit: oemlogkit: !start_log, sleep
08-25 23:34:02.118  1580  3437 I ActivityTaskManager: START u0 {act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/*} from uid 10280 pid 20216
08-25 23:34:02.119 20216 20216 D AndroidRuntime: Shutting down VM
08-25 23:34:02.119 20216 20216 E AndroidRuntime: FATAL EXCEPTION: main
08-25 23:34:02.119 20216 20216 E AndroidRuntime: Process: net.frju.flym, PID: 20216
08-25 23:34:02.119 20216 20216 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* }
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2248)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1902)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5231)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(SourceFile:6)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5189)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(SourceFile:3)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at net.frju.flym.ui.main.MainActivity.pickOpml(SourceFile:4)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at net.frju.flym.ui.main.MainActivity.access$pickOpml(SourceFile:1)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at net.frju.flym.ui.main.MainActivity$onCreate$1$$special$$inlined$let$lambda$1.onMenuItemClick(SourceFile:6)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(SourceFile:2)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(SourceFile:1)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(SourceFile:2)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:4)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(SourceFile:6)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3265)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7711)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
08-25 23:34:02.119 20216 20216 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-25 23:34:02.122  1580 21024 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-25 23:34:02.122  1580  5673 W ActivityTaskManager:   Force finishing activity net.frju.flym/.ui.main.MainActivity
08-25 23:34:02.123  1580 21024 D FrameworkEventCollector: recordAppIssue PN: net.frju.flym
08-25 23:34:02.124  1580  5673 E ScreenModeService: getAppToken AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}}
08-25 23:34:02.124  1580  5673 E ScreenModeService: setRefreshRate token AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}} rate 0 tmpRate 0
08-25 23:34:02.124  1580  5381 D tiw     : OS Event: crash
08-25 23:34:02.124  1580  5673 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}} pkgName net.oneplus.launcher
08-25 23:34:02.124  1580  5673 E ScreenModeService: getAppToken AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}}
08-25 23:34:02.125  1580  5673 E ScreenModeService: setRefreshRate token AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}} rate 0 tmpRate 0
08-25 23:34:02.125  1580  5673 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{f565868 token=Token{fd7ff8b ActivityRecord{9b7115a u0 net.oneplus.launcher/.Launcher t226}}} pkgName net.oneplus.launcher
08-25 23:34:02.128  1580 21024 D DropBoxManagerService: Copy /data/system/dropbox/data_app_crash@2020-08-25-23_34_02_127.txt to /data/oem_log/
08-25 23:34:02.132  1580  5673 D OpTaskSnapshotControllerInjector: LetterBox insets empty
08-25 23:34:02.133  1580  5673 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
08-25 23:34:02.139 20216 21007 D ViewRootImpl[PopupWindow:1f330b3]: windowFocusChanged hasFocus=false inTouchMode=true
08-25 23:34:02.146  1580  1580 D gwy     : Event success
08-25 23:34:02.148  1580  1701 I ActivityManager: Showing crash dialog for package net.frju.flym u0
08-25 23:34:02.149  1580  1715 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-25 23:34:02.149  1580  1715 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-25 23:34:02.149  1580  1715 D Foreground_io: TOP_APP is ProcessRecord{2c831c8 4503:net.oneplus.launcher/u0a131} uid is 10131
08-25 23:34:02.149  1580  1702 D Foreground_io: Setting fg uid
08-25 23:34:02.150  1580  1702 D Foreground_io: Set up
08-25 23:34:02.179  1580  1703 D ViewRootImpl[flym]: windowFocusChanged hasFocus=true inTouchMode=true
08-25 23:34:02.183  1580  1727 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
08-25 23:34:02.193  4503  4529 W System  : A resource failed to call release. 
08-25 23:34:02.194  4503  4529 W System  : A resource failed to call release. 
08-25 23:34:02.213  1580  1714 D ExtBatteryStatsService: @@@@ awaitUninterruptibly in 31 ms
08-25 23:34:02.213  1580  1714 D MyBatteryStatsHelper: ===processSingleAppUsage===
08-25 23:34:02.214  1580  1714 D ExtBatteryStatsService: ext-flush too soon, skip
08-25 23:34:02.214  1580  1714 D MyBatteryStatsHelper: ===processSingleAppUsage===
08-25 23:34:02.624  1580  1703 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{4cb98f2 u0 net.frju.flym/.ui.main.MainActivity t268 f}
08-25 23:34:02.634  1580  1703 W ActivityTaskManager: Activity pause timeout for ActivityRecord{4cb98f2 u0 net.frju.flym/.ui.main.MainActivity t268 f}
```

</details>

You can always ask if you need more information, I'm happy to provide it.

**Comment by AlexanderRitter02** [comment]
- App version: 2.4.0
- Android: 10
- Device: OnePlus Nord
- Installed from F-Droid.
