### ISSUE TITLE
Crash when swiping unread messages

### ISSUE THREAD

**Issue by s-ki** [FredJul/Flym#673]
Since 2.5.0 (still happening in 2.5.1) the app crashes on my phone when swiping an unread message out of the list:

2020-09-17 18:04:07.102 32732-32732/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.frju.flym, PID: 32732
    java.lang.NullPointerException: null cannot be cast to non-null type com.google.android.material.behavior.HideBottomViewOnScrollBehavior<android.view.View!>
        at net.frju.flym.ui.entries.EntriesFragment.showNavigationIfRecyclerViewCannotScroll(SourceFile:6)
        at net.frju.flym.ui.entries.EntriesFragment.access$showNavigationIfRecyclerViewCannotScroll(SourceFile:1)
        at net.frju.flym.ui.entries.EntriesFragment$setupRecyclerView$itemTouchHelperCallback$1$onSwiped$$inlined$let$lambda$1$2.invoke(SourceFile:2)
        at net.frju.flym.ui.entries.EntriesFragment$setupRecyclerView$itemTouchHelperCallback$1$onSwiped$$inlined$let$lambda$1$2.invoke(SourceFile:1)
        at org.jetbrains.anko.AsyncKt$uiThread$1.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
2020-09-17 18:04:07.113 3242-3688/? W/ActivityManager:   Force finishing activity net.frju.flym/.ui.main.MainActivity

I'm running Android 9 on a Motorola Moto G6.

**Comment by FredJul** [comment]
Thanks, the bug has been fixed and a new version in publishing on Play Store, you should receive it in a few hours maximum.

Sorry for the inconveniences.

**Comment by s-ki** [comment]
Excellent, thanks!
